USE [MS_HF_MART]
GO

/* Extend fee columns to decimal(38,6) start */

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_PRODUCT_FEE_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_PRODUCT_FEE_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_PRODUCT_FEE_AMT] TO decimal(38,6)'
END

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_PRODUCT_FEE_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_PRODUCT_FEE_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_PRODUCT_FEE_AMT] TO decimal(38,6)'
END

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_TOTAL_FEE_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_TOTAL_FEE_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_TOTAL_FEE_AMT] TO decimal(38,6)'
END

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_HUNT_FEE_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_HUNT_FEE_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_HUNT_FEE_AMT] TO decimal(38,6)'
END

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_STATE_TXN_FEE_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_STATE_TXN_FEE_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_STATE_TXN_FEE_AMT] TO decimal(38,6)'
END

IF EXISTS(select * from sysobjects a,syscolumns b,systypes c where a.id=b.id and a.name='RPT_SALES_TRANSACTION' and a.xtype='U' and b.name = 'ADJUSTED_TAX_AMT' and b.xtype=c.xtype and b.prec = 20 and b.scale = 2 and c.name = 'numeric')
BEGIN
	ALTER TABLE DBO.RPT_SALES_TRANSACTION ALTER COLUMN ADJUSTED_TAX_AMT decimal(38,6) null
	PRINT '[INFO] ALTER COLUMN [DBO].[RPT_SALES_TRANSACTION].[ADJUSTED_TAX_AMT] TO decimal(38,6)'
END

/* Extend fee columns to decimal(38,6) end */


IF NOT EXISTS( SELECT TOP 1 1 FROM sys.indexes i WHERE i.object_id = object_id('[dbo].[RPT_SALES_TRANSACTION]','U') AND i.name = 'RPT_SALES_TRANSACTION_PRODUCT_KEY_IX')
BEGIN
    CREATE NONCLUSTERED INDEX [RPT_SALES_TRANSACTION_PRODUCT_KEY_IX] ON [dbo].[RPT_SALES_TRANSACTION](D_PRODUCT_KEY) ON MS_HF_MART_IDX
    PRINT '[INFO] CREATED NONCLUSTERED INDEX [dbo].[RPT_SALES_TRANSACTION].[RPT_SALES_TRANSACTION_PRODUCT_KEY_IX]'
END
GO

IF NOT EXISTS( SELECT TOP 1 1 FROM sys.indexes i WHERE i.object_id = object_id('[dbo].[RPT_SALES_TRANSACTION]','U') AND i.name = 'RPT_SALES_TRANSACTION_ISSUE_CUSTOMER_PROFILE_KEY_IX')
BEGIN
    CREATE NONCLUSTERED INDEX [RPT_SALES_TRANSACTION_ISSUE_CUSTOMER_PROFILE_KEY_IX] ON [dbo].[RPT_SALES_TRANSACTION](ISSUE_CUSTOMER_PROFILE_KEY) ON MS_HF_MART_IDX
    PRINT '[INFO] CREATED NONCLUSTERED INDEX [dbo].[RPT_SALES_TRANSACTION].[RPT_SALES_TRANSACTION_ISSUE_CUSTOMER_PROFILE_KEY_IX]'
END
GO

IF NOT EXISTS( SELECT TOP 1 1 FROM sys.indexes i WHERE i.object_id = object_id('[dbo].[RPT_SALES_TRANSACTION]','U') AND i.name = 'RPT_SALES_TRANSACTION_AWO_ORDER_CUSTOMER_PROFILE_ID_IX')
BEGIN
    CREATE NONCLUSTERED INDEX [RPT_SALES_TRANSACTION_AWO_ORDER_CUSTOMER_PROFILE_ID_IX] ON [dbo].[RPT_SALES_TRANSACTION](AWO_ORDER_CUSTOMER_PROFILE_ID) ON MS_HF_MART_IDX
    PRINT '[INFO] CREATED NONCLUSTERED INDEX [dbo].[RPT_SALES_TRANSACTION].[RPT_SALES_TRANSACTION_AWO_ORDER_CUSTOMER_PROFILE_ID_IX]'
END
GO

IF NOT EXISTS(SELECT * from dbo.syscolumns WHERE id=object_id('RPT_SALES_TRANSACTION') AND name='ORDER_ITEM_ID')
BEGIN
	ALTER TABLE RPT_SALES_TRANSACTION ADD ORDER_ITEM_ID int NULL
	PRINT '[INFO] ADD COLUMN [DBO].[RPT_SALES_TRANSACTION].[ORDER_ITEM_ID]'
END

IF NOT EXISTS(SELECT * from dbo.syscolumns WHERE id=object_id('RPT_SALES_TRANSACTION') AND name='D_ORDER_STATE_KEY')
BEGIN
	ALTER TABLE RPT_SALES_TRANSACTION ADD D_ORDER_STATE_KEY int NULL
	PRINT '[INFO] ADD COLUMN [DBO].[RPT_SALES_TRANSACTION].[D_ORDER_STATE_KEY]'
END

IF NOT EXISTS(SELECT * from dbo.syscolumns WHERE id=object_id('RPT_SALES_TRANSACTION') AND name='REFUND_IND')
BEGIN
	ALTER TABLE RPT_SALES_TRANSACTION ADD REFUND_IND int NULL
	PRINT '[INFO] ADD COLUMN [DBO].[RPT_SALES_TRANSACTION].[REFUND_IND]'
END

IF NOT EXISTS(SELECT * from dbo.syscolumns WHERE id=object_id('RPT_SALES_TRANSACTION') AND name='PURCHASE_TYPE_NM')
BEGIN
	ALTER TABLE RPT_SALES_TRANSACTION ADD PURCHASE_TYPE_NM varchar(100) NULL
	PRINT '[INFO] ADD COLUMN [DBO].[RPT_SALES_TRANSACTION].[PURCHASE_TYPE_NM]'
END

IF NOT EXISTS(SELECT * from dbo.syscolumns WHERE id=object_id('RPT_SALES_TRANSACTION') AND name='D_STORE_KEY')
BEGIN
	ALTER TABLE RPT_SALES_TRANSACTION ADD D_STORE_KEY int NULL
	PRINT '[INFO] ADD COLUMN [DBO].[RPT_SALES_TRANSACTION].[D_STORE_KEY]'
END
