USE [MS_HF_MART]
GO
/****** Object:  Table [dbo].[RPT_SALES_TRANSACTION]    Script Date: 8/21/2019 5:11:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[RPT_SALES_TRANSACTION](
	[RPT_SALES_TRANSACTION_KEY] [int] IDENTITY(1,1) NOT NULL,
	[QUANTITY_CNT] [numeric](38, 4) NULL,
	[ADJUSTED_PRODUCT_FEE_AMT] [numeric](20, 2) NULL,
	[ADJUSTED_POS_TXN_FEE_AMT] [numeric](20, 2) NULL,
	[ADJUSTED_TOTAL_FEE_AMT] [numeric](20, 2) NULL,
	[D_PRODUCT_KEY] [int] NULL,
	[PRODUCT_CD] [varchar](255) NULL,
	[PRODUCT_NM] [varchar](255) NULL,
	[PRODUCT_CLASS_NM] [varchar](100) NULL,
	[PRODUCT_CATEGORY_NM] [varchar](100) NULL,
	[TRANSACTION_TYPE_NM] [varchar](100) NULL,
	[ADJUSTED_ORDER_DATE_KEY] [int] NULL,
	[LOCATION_CLASS_NAME] [varchar](100) NULL,
	[STORE_NM] [varchar](255) NULL,
	[STORE_ID] [varchar](255) NULL,
	[OLD_AGENT_ID] [varchar](256) NULL,
	[AWO_TRANSACTION_ID] [int] NULL,
	[REPORT_CATEGORY_NM] [varchar](100) NULL,
	[ADJUSTED_HUNT_FEE_AMT] [numeric](20, 2) NULL,
	[D_TRANSACTION_TYPE_KEY] [int] NULL,
	[ADJUSTED_TRANS_DATE_KEY] [int] NULL,
	[AWO_PRODUCT_ID] [int] NULL,
	[ISSUE_CUSTOMER_PROFILE_KEY] [int] NULL,
	[D_RESIDENT_TYPE_KEY] [int] NULL,
	[FISCAL_YR] [int] NULL,
	[AWO_ORDER_CUSTOMER_PROFILE_ID] [int] NULL,
	[ADJUSTED_STATE_TXN_FEE_AMT] [numeric](20, 2) NULL,
	[ADJUSTED_TAX_AMT] [numeric](20, 2) NULL,
	[PRIVILEGE_LICENSE_YR] [int] NULL
) ON [MS_HF_MART_201502_IDX]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Index [RPT_SALES_TRANSACTION_ORDER_DT_IX]    Script Date: 8/21/2019 5:11:53 PM ******/
CREATE CLUSTERED INDEX [RPT_SALES_TRANSACTION_ORDER_DT_IX] ON [dbo].[RPT_SALES_TRANSACTION]
(
	[ADJUSTED_ORDER_DATE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [MS_HF_MART_201502_IDX]
GO
/****** Object:  Index [RPT_SALES_TRANSACTION_ADJUSTED_TRANS_DATE_KEY_IX]    Script Date: 8/21/2019 5:11:53 PM ******/
CREATE NONCLUSTERED INDEX [RPT_SALES_TRANSACTION_ADJUSTED_TRANS_DATE_KEY_IX] ON [dbo].[RPT_SALES_TRANSACTION]
(
	[ADJUSTED_TRANS_DATE_KEY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [MS_HF_MART_201502_IDX]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'License year of the product when purchased.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'RPT_SALES_TRANSACTION', @level2type=N'COLUMN',@level2name=N'PRIVILEGE_LICENSE_YR'
GO
